# .travis.yml

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/DateInRegion.xcworkspace -scheme DateInRegion-Example -configuration Debug -destination "platform=iOS Simulator,name=iPhone 5s,OS=9.0" -destination "platform=iOS Simulator,name=iPhone 6s plus,OS=9.1" -parallelizeTargets ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES | xcpretty -c
- pod lib lint
